#!/usr/bin/env node

var fs = require('fs')

var logger = fs.createWriteStream('.gitignore', {
  flags: 'a' // 'a' means appending (old data will be preserved)
})

logger.write('# OSX \n')
logger.write('# \n')
logger.write('.DS_Store \n')
logger.write('\n')
logger.write('# Xcode \n')
logger.write('# \n')
logger.write('build/ \n')
logger.write('*.pbxuser \n')
logger.write('!default.pbxuser \n')
logger.write('*.mode1v3 \n')
logger.write('!default.mode1v3 \n')
logger.write('*.mode2v3 \n')
logger.write('!default.mode2v3 \n')
logger.write('*.perspectivev3 \n')
logger.write('!default.perspectivev3 \n')
logger.write('xcuserdata \n')
logger.write('*.xccheckout \n')
logger.write('*.moved-aside \n')
logger.write('DerivedData \n')
logger.write('*.hmap \n')
logger.write('*.ipa \n')
logger.write('*.xcuserstate \n')
logger.write('\n')
logger.write('# Android/IntelliJ \n')
logger.write('# \n')
logger.write('build/ \n')
logger.write('.idea \n')
logger.write('.gradle \n')
logger.write('local.properties \n')
logger.write('*.iml \n')
logger.write('\n')
logger.write('# node.js \n')
logger.write('# \n')
logger.write('node_modules/ \n')
logger.write('npm-debug.log \n')
logger.write('yarn-error.log \n')
logger.write('\n')
logger.write('# BUCK \n')
logger.write('buck-out/ \n')
logger.write('\.buckd/ \n')
logger.write('# *.keystore \n')
logger.write('# !debug.keystore \n')
logger.write('\n')
logger.write('# fastlane \n')
logger.write('# \n')
logger.write('# It is recommended to not store the screenshots in the git repo. Instead, use fastlane to re-generate the \n')
logger.write('# screenshots whenever they are needed. \n')
logger.write('# For more information about the recommended setup visit: \n')
logger.write('# https://docs.fastlane.tools/best-practices/source-control/ \n')
logger.write('\n')
logger.write('*/fastlane/report.xml \n')
logger.write('*/fastlane/Preview.html \n')
logger.write('*/fastlane/screenshots \n')
logger.write('\n')
logger.write('# Bundle artifact \n')
logger.write('*.jsbundle \n')
logger.write('\n')
logger.write('# CocoaPods \n')
logger.write('/ios/Pods/ \n')